services:
    postgres-db:
        image: postgres:18
        container_name: postgres_container
        shm_size: 128mb
        entrypoint: >
            sh -c "chmod +x /docker-entrypoint-initdb.d/init-wrapper.sh
            && exec /usr/local/bin/docker-entrypoint.sh postgres"
        environment:
            POSTGRES_USER_FILE: /run/secrets/db_super_user
            POSTGRES_PASSWORD_FILE: /run/secrets/db_super_password
            POSTGRES_DB_FILE: /run/secrets/db_default_name
        ports:
            - "${DB_PORT_EXTERNAL}:5432"
        volumes:
            - ./infra/data:/var/lib/postgresql
            - ./infra/init-wrapper.sh:/docker-entrypoint-initdb.d/init-wrapper.sh
        secrets:
            - db_super_user
            - db_super_password
            - db_default_name
            - products_db_user
            - products_db_password
            - products_db_name
            - clients_db_user
            - clients_db_password
            - clients_db_name
            - orders_db_user
            - orders_db_password
            - orders_db_name
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 15s

    product-service:
        build: ./products
        image: rodrigodip/product-service:1.0.0
        container_name: product_service_app
        ports:
            - "${PRODUCTS_PORT_EXTERNAL}:8081"
        environment:
            DB_HOST: postgres-db
            DB_PORT: "5432"
        secrets:
            - products_db_user
            - products_db_password
            - products_db_name
        depends_on:
            postgres-db:
                condition: service_healthy

    client-service:
        build: ./clients
        image: rodrigodip/clients-service:1.0.0
        container_name: client_service_app
        ports:
            - "${CLIENTS_PORT_EXTERNAL}:8082"
        environment:
            DB_HOST: postgres-db
            DB_PORT: "5432"
        secrets:
            - clients_db_user
            - clients_db_password
            - clients_db_name
        depends_on:
            postgres-db:
                condition: service_healthy

    order-service:
        build: ./orders
        image: rodrigodip/orders-service:1.0.0
        container_name: order_service_app
        ports:
            - "${ORDERS_PORT_EXTERNAL}:8083"
        environment:
            DB_HOST: postgres-db
            DB_PORT: "5432"
            PRODUCTS_BASE_URL: ${PRODUCTS_BASE_URL:-http://product-service:8081}
            CLIENTS_BASE_URL: ${CLIENTS_BASE_URL:-http://client-service:8082}
        secrets:
            - orders_db_user
            - orders_db_password
            - orders_db_name
        depends_on:
            postgres-db:
                condition: service_healthy

secrets:
    db_super_user:
        file: ./infra/secrets/db_super_user
    db_super_password:
        file: ./infra/secrets/db_super_password
    db_default_name:
        file: ./infra/secrets/db_default_name
    products_db_user:
        file: ./infra/secrets/products_db_user
    products_db_password:
        file: ./infra/secrets/products_db_password
    products_db_name:
        file: ./infra/secrets/products_db_name
    clients_db_user:
        file: ./infra/secrets/clients_db_user
    clients_db_password:
        file: ./infra/secrets/clients_db_password
    clients_db_name:
        file: ./infra/secrets/clients_db_name
    orders_db_user:
        file: ./infra/secrets/orders_db_user
    orders_db_password:
        file: ./infra/secrets/orders_db_password
    orders_db_name:
        file: ./infra/secrets/orders_db_name
