services:
    postgres-db:
        image: postgres:18
        container_name: postgres_container
        shm_size: 128mb
        entrypoint: >
            sh -c "chmod +x /docker-entrypoint-initdb.d/init-wrapper.sh
            && exec /usr/local/bin/docker-entrypoint.sh postgres"
        environment:
            POSTGRES_USER_FILE: /run/secrets/db_super_user
            POSTGRES_PASSWORD_FILE: /run/secrets/db_super_password
            POSTGRES_DB_FILE: /run/secrets/db_default_name
        ports:
            - "${DB_PORT_EXTERNAL}:5432"
        volumes:
            - ./infra/data:/var/lib/postgresql
            - ./infra/init-wrapper.sh:/docker-entrypoint-initdb.d/init-wrapper.sh
        secrets:
            - db_super_user
            - db_super_password
            - db_default_name
            - produtos_db_user
            - produtos_db_password
            - produtos_db_name
            - clientes_db_user
            - clientes_db_password
            - clientes_db_name
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 15s

    produto-service:
        build: ./products
        image: rodrigodip/produto-service:1.0.0
        container_name: produto_service_app
        ports:
            - "${PRODUTOS_PORT_EXTERNAL}:8081"
        environment:
            DB_HOST: postgres-db
            DB_PORT: "5432"
        secrets:
            - produtos_db_user
            - produtos_db_password
            - produtos_db_name
        depends_on:
            postgres-db:
                condition: service_healthy

    cliente-service:
        build: ./clients
        image: rodrigodip/cliente-service:1.0.0
        container_name: cliente_service_app
        ports:
            - "${CLIENTES_PORT_EXTERNAL}:8082"
        environment:
            DB_HOST: postgres-db
            DB_PORT: "5432"
        secrets:
            - clientes_db_user
            - clientes_db_password
            - clientes_db_name
        depends_on:
            postgres-db:
                condition: service_healthy

secrets:
    db_super_user:
        file: ./infra/secrets/db_super_user
    db_super_password:
        file: ./infra/secrets/db_super_password
    db_default_name:
        file: ./infra/secrets/db_default_name
    produtos_db_user:
        file: ./infra/secrets/produtos_db_user
    produtos_db_password:
        file: ./infra/secrets/produtos_db_password
    produtos_db_name:
        file: ./infra/secrets/produtos_db_name
    clientes_db_user:
        file: ./infra/secrets/clientes_db_user
    clientes_db_password:
        file: ./infra/secrets/clientes_db_password
    clientes_db_name:
        file: ./infra/secrets/clientes_db_name
