services:
    postgres-db:
        image: postgres:18
        container_name: postgres_dev_container
        shm_size: 128mb
        entrypoint: >
            sh -c "chmod +x /docker-entrypoint-initdb.d/init-wrapper.sh
            && exec /usr/local/bin/docker-entrypoint.sh postgres"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: super_senha_geral
            POSTGRES_DB: default_db
            PRODUCTS_DB_USER: product_user
            PRODUCTS_DB_PASSWORD: senha_products_123
            PRODUCTS_DB_NAME: products
            CLIENTS_DB_USER: client_user
            CLIENTS_DB_PASSWORD: senha_clients_123
            CLIENTS_DB_NAME: clients
        ports:
            - "5555:5432"
        volumes:
            - ./infra/data_dev:/var/lib/postgresql
            - ./infra/init-wrapper.sh:/docker-entrypoint-initdb.d/init-wrapper.sh
        restart: unless-stopped
