-- ================================================================ --
-- PLACED -> Order placed/created by customer
-- PAID -> Payment confirmed
-- INVOICED -> Invoice issued
-- SHIPPED -> Order shipped
-- PAYMENT_FAILED -> Payment failed
-- PREPARING_SHIPMENT -> Order being prepared for shipping
-- ================================================================ --

CREATE TABLE orders(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    order_date TIMESTAMP NOT NULL DEFAULT now(),
    payment_key TEXT,
    status varchar(20) NOT NULL DEFAULT 'PLACED' CHECK ( 
      status in (
        'PLACED',
        'PAID',
        'INVOICED',
        'SHIPPED',
        'PAYMENT_FAILED',
        'PREPARING_SHIPMENT'
      )
    ),
    notes TEXT,
    total NUMERIC(16,2) NOT NULL,
    tracking_code VARCHAR (255),
    invoice_url TEXT
);

CREATE INDEX idx_orders__client_id on orders(client_id);

CREATE TABLE order_items(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL references orders (id),
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    unit_price NUMERIC(16,2) NOT NULL
);

CREATE INDEX idx_order_items__order_id on order_items(order_id);
CREATE INDEX idx_order_items__product_id on order_items(product_id);