services:
    postgres-db:
        image: postgres:18
        container_name: postgres_dev_container
        shm_size: 128mb
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: super_senha_geral
            POSTGRES_DB: default_db
        ports:
            - "5555:5432" # Expõe a 5555 para a sua máquina física conectar
        volumes:
            - ./data_dev:/var/lib/postgresql
            - ./init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql:ro
        restart: unless-stopped
