spring:
    config:
        import: "optional:configtree:/run/secrets/"
    application:
        name: clients
    datasource:
        url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5555}/${clientes_db_name:clients}"
        username: "${clientes_db_user:client_user}"
        password: "${clientes_db_password:senha_clientes_123}"
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                "[format_sql]": true
    flyway:
        enabled: true
        baseline-on-migrate: true
server:
    port: 8082
